### ISSUE TITLE
Removing a rule from repo does not delete rule in Auth0

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-extensions/auth0-deploy-extensions#18]
As the title says:
- create a new rule via git repo, push it- > it's created in Auth0
- delete the rule in git repo, push it -> **rule remains in Auth0**

Tested with the Visual Studio extension using Azure DevOps. 

I know you can use the .json-metafile and enable/disable rules, but I actually want the rule to be really deleted.

**Comment by malhotraashna** [comment]
@zxan1285 I am trying to delete rule config using auth0-deploy extension in CI. I deleted some rule configs from the Git repo which is then being deployed using auth0 extension but the rule configs still exist in target tenant even when I have `AUTH0_ALLOW_DELETE` set to `true` in `config.js`. Any suggestion on how to make it work?

**Comment by zxan1285** [comment]
@malhotraashna the extensions does not remove rule configs. Deploy tools can only create/update those.
You can either remove rule config manually from dashboard, or by using management API - https://auth0.com/docs/api/management/v2#!/Rules_Configs/delete_rules_configs_by_key.

**Comment by malhotraashna** [comment]
@zxan1285 Is there any specific reason for this limitation? Or do you consider supporting it sometime?

**Comment by zxan1285** [comment]
@malhotraashna rules configs cannot be exported (you cannot GET rules configs from API). Because of that, we cannot consider the repo as the only source of truth for the rules configs. Accidental removal of the rule config can potentially cause serious issues. As far as i know, we're not going to support that in near future.

**Comment by zxan1285** [comment]
The original issue (extension does not remove rules) has been fixed with publishing of `auth0-source-control-extension-tools@3.4.0`.
