### ISSUE TITLE
Deploy Roles

### ISSUE THREAD

**Issue by harmon25** [auth0-extensions/auth0-deploy-extensions#22]
It would be nice to also deploy RBAC roles/permissions via this extension. 

Can be implemented same as everything else.

I.E A `roles` folder - with with multiple json files:

`some-role.json`

```json
{ "name": "Some Role", "description": "Some Role Description"}
```

or a single json array

`roles.json`

```json
[
  { "name": "Some Role", "description": "Some Role Description"},
  { "name": "Another Role", "description": "Another Role Description"}
]
```
And something similar for permissions.

Thanks!

**Comment by christophano** [comment]
I'd like to see this too.
Permissions are properties of a resource server/api, so are already managed vie these extensions.

**Comment by nfadili** [comment]
The management API [supports role management](https://auth0.com/docs/api/management/v2#!/Roles/get_roles) so this seems within the scope of these extensions. Is this planned to be supported?
