### ISSUE TITLE
Feature request: Support for APIs

### ISSUE THREAD

**Issue by goodspark** [auth0-extensions/auth0-deploy-extensions#27]
That is, this stuff:
![Screenshot from 2019-05-28 09-33-20](https://user-images.githubusercontent.com/29210237/58495178-aa2a8180-812b-11e9-894b-a817510d6801.png)

I used the CLI deploy tool to output my current tenant's configuration to see if there's an obvious way to add the Auth0 API (including custom ones in the future) into my code config, but I don't see anything obvious. Here's what my output looks like:

![Screenshot from 2019-05-28 09-39-02](https://user-images.githubusercontent.com/29210237/58495475-74d26380-812c-11e9-9d2f-c3c3f3ffad85.png)

I can't find anything in this directory tree is there anything for the APIs.

**Comment by fyockm** [comment]
`resource-servers` == `apis`

**Comment by goodspark** [comment]
There's nothing for auth0 API in that directory.

**Comment by francipvb** [comment]
Hello,

I tried to deploy resource-servers but my files don't appear in apis section of the dashboard.

Cheers,

**Comment by zxan1285** [comment]
@francipvb hey. What do you have in `resource-servers` dir?
This is how it should look:
`resource-servers/some-api.json`
```
{
  "name": "some-api",
  "identifier": "some-identifier",
  "scopes": [
      {
        "description": "create something",
        "value": "create:something"
      },
      {
        "description": "read something",
        "value": "read:something"
      },
      {
        "description": "update something",
        "value": "update:something"
      },
      {
        "description": "delete something",
        "value": "delete:something"
      }
  ]
}
```

**Comment by francipvb** [comment]
Thanks, I was wrong about this.

Cheers.

**Comment by francipvb** [comment]
Hello all,

In my case I solved my problem. Thanks for your help.

Cheers,
