### ISSUE TITLE
Azure Devops - Supported?

### ISSUE THREAD

**Issue by yoadsn** [auth0-extensions/auth0-deploy-extensions#30]
Hi,
Seems like the integration with Azure Devops is not really working.
Bottom line - configuration will not affect the basic error of accessing the prop "value" on undefined..
This fails in the Azure Devops API node lib..

Before I try and debug deeper on this - is this even supposed to work?

**Comment by zxan1285** [comment]
Hi @yoadsn 
The extension is supposed to work with Azure Devops. 

Could you please check the `INSTANCE` secret in the extension configuration?
This secret should not contain protocol and `.visualstudio.com` or `dev.azure.com` in it. For `my-company.visualstudio.com`/`dev.azure.com/my-company` the secret should be just `my-company`.

**Comment by yoadsn** [comment]
Thanks @zxan1285!
After un-installing the extension (for the 2nd time) and re-entering all the data - It just works.
I must have missed something on the earlier attempts.

One clear conclusion is that if migrating from V2.2 (maybe also V2.3) - Need to uninstall and not just update. Otherwise the configuration is messed up.

Closing this - Thanks again!
