### ISSUE TITLE
Question: How to grant Auth0 Management API scopes independent of the tenant?

### ISSUE THREAD

**Issue by ghost** [auth0-extensions/auth0-deploy-extensions#37]
Given each Auth0 tenant has a System API called 'Auth0 Management API', I was wondering if there is a generic way to get this API's audience.

I'm trying to create a repository which has the `develop` branch deployed to one Auth0 tenant and `master` to another, but if I specify the develop tenant's Auth0 Management API identifier in the `grants/myorg.json` file then the deployment fails in the other environment because the API is not found. 

For example:

``` json
//myorg.json
{
  "client_id": "My Machine to Machine client",
    "audience": "https://{develop-myorg|myorg}.eu.auth0.com/api/v2/",
    "scope": [
      "read:users"
    ]
}
```
I'd like to use exactly the same Auth0 configuration in both environments so I can catch any configuration errors before they hit production.

**Comment by zxan1285** [comment]
[Keyword mappings](https://auth0.com/docs/extensions/deploy-cli/references/environment-variables-keyword-mappings) should help with this. 

```
// config.json
{
  ...
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "TENANT": "myorg" // "develop-myorg" for dev-config.json
  }
}
```

```
//myorg.json
{
  "client_id": "My Machine to Machine client",
    "audience": "https://#TENANT#.eu.auth0.com/api/v2/",
    "scope": [
      "read:users"
    ]
}
```

**Comment by ghost** [comment]
Thanks @zxan1285, I hadn't found keyword mappings; they will definitely help here. I'm still missing one piece of information: how can I specify which config.json file to use for each tenant? If I was to make a call using the CLI I could add `-c {dev-}config.json`, but the GitHub Deployments extension doesn't seem to be picking up a `config.json` file at the root level, and I can't see any information about specifying the config.json file.

I can see that someone else had the same issue as me 11 days ago and decided not to use the GitHub Deployments extension because he couldn't find a solution: https://community.auth0.com/t/parameterized-deployments-using-github-deploy-tool/29527/5

**Comment by zxan1285** [comment]
Hey @joe-eequ 
I'm currently working on major update for GitHub Deployments extension, the update will include keyword mappings support. The work is almost done, and i hope to publish it next week.

**Comment by ghost** [comment]
Hey @zxan1285, that's awesome! Look forward to checking it out.

**Comment by ghost** [comment]
Hey @zxan1285, I've just deployed to my tenant using Keyword Mappings in the GitHub Deployments extension. Thanks for your help.
