### ISSUE TITLE
Issue with bitbucket deployment extension

### ISSUE THREAD

**Issue by HelloAndrewNgo** [auth0-extensions/auth0-deploy-extensions#38]
Hi Auth0 Team,

I've been unable to deploy using the bitbucket deployment extension. The only logs I receive is "Request failed with status code 401."

![image](https://user-images.githubusercontent.com/37164595/64557143-cc6c9780-d2f5-11e9-82fa-025d1c05586b.png)

I've tried redeploying to an auth0 tenant with a previously successful deployment and still failed. No changes or configurations were changed for this auth0 tenant.

![image](https://user-images.githubusercontent.com/37164595/64556886-30429080-d2f5-11e9-8307-463a419f3aa0.png)

Any help would be appreciated.

**Comment by zxan1285** [comment]
Hey @AndrewTruongNgo 
`Request failed with status code 401` is the bitbucket api response. Could you please update your bitbucket password in the extension settings?

**Comment by HelloAndrewNgo** [comment]
Hi @zxan1285 
Thank you so much, your solution worked! I'll be sure to do this if I get this error again 👍🏼
