### ISSUE TITLE
Recent changes to cipher functionality have broken deployments

### ISSUE THREAD

**Issue by nfadili** [auth0-extensions/auth0-deploy-extensions#39]
As of about a week ago, our deployments have failed with the error `Libsodium error: Error: wrong secret key for the given ciphertext`. My first thought was that someone must have accidentally changed our tenant's cipher secret. When I went to check it in the extension configuration menu I noticed that the 'Cipher Secret' input field is completely gone. We are using v2.10 of the extension.

Looking through the changelog and and commit history of this repo, I see that cipher secrets are being replaced with something called 'mappings'. Since we have not updated the extension to v3.0, I believe the latest release might have accidentally broken tenants configured with v2 installations.

Guidance on fixing this would be very appreciated. We would like to keep all configurations in version control (including encrypted secrets) instead of updating them in the management dashboard.

**Comment by shawnmclean** [comment]
Hi @nfadili, we have made a change on the dashboard to accommodate backwards compatibility of older extensions.

Please reopen if you still face this issue.
