### ISSUE TITLE
Mappings not working on Email Provider credentials

### ISSUE THREAD

**Issue by jeremyfordip** [auth0-extensions/auth0-deploy-extensions#42]
The problem I found was that trying to use the ##MAPPING## syntax for the smtp password did not work as expected using the Bitbucket deploy extension.

Here is the example provider.json I was trying to use:

```json
{
  "name": "smtp",
  "enabled": true,
  "default_from_address": "no-reply@somewhere.com",
  "credentials": {
    "smtp_host": "smtp.sendgrid.net",
    "smtp_port": 587,
    "smtp_user": "apikey",
    "smtp_pass": "##SMTP_PASSWORD##"
  }
}
```

The configured mappings are

```json
{
  "SMTP_PASSWORD": "super secret password"
}
```

After a "successful deployment the email sending fails due to incorrect password.

I cloned the repo and added some tests.
It looks like the "applyMapping" function in utils.js (server/lib/utils.js) is not correctly handling the credentials item/key.

```javascript
const applyMappings = (item, mappings) => {
  const result = {};
  Object.keys(item).forEach((key) => {
    if (Array.isArray(item[key])) {
      const value = item[key];
      result[key] = JSON.parse(keywordReplace(JSON.stringify(value), mappings));
    } else {
      //START CHANGE
      if (typeof item[key] === 'string') {
        result[key] = keywordReplace(item[key], mappings);
      } else {
        //This code gets executed and correctly processes for emailProvider credentials
        result[key] = JSON.parse(keywordReplace(JSON.stringify(item[key]), mappings));
      }
      //END CHANGE
    }
  });
  console.log('applyMappings Result: ' + JSON.stringify(result));
  return result;
};

```
After making the above (not so nice!) change it processes the template correctly.

**Comment by cderche** [comment]
I am having a similar issue with mailgun.

I have my `provider.json`:
```json
{
  "enabled": true,
  "credentials": {
    "api_key": "##MAILGUN_API_KEY##",
    "domain": "##MAILGUN_DOMAIN##"
  },
  "name": "mailgun",
  "default_from_address": "##MAILGUN_EMAIL##"
}
```

In mappings I have defined:
- MAILGUN_API_KEY
- MAILGUN_DOMAIN
- MAILGUN_EMAIL

Both `MAILGUN_DOMAIN` and `MAILGUN_EMAIL` work, but `MAILGUN_API_KEY` seems to be converted into something else because the provider test email doesn't work.
