### ISSUE TITLE
Provide a means to deploy encrypted secrets for rules and DB scripts

### ISSUE THREAD

**Issue by goodspark** [auth0-extensions/auth0-deploy-extensions#5]
I'd like to keep all my configuration and secrets in version control to minimize human error when updating auth0 settings.

Obviously we shouldn't store secrets in plain text. So that leaves encryption.

Something like [sops](https://github.com/mozilla/sops) or similar would be perfect. But presumably the keys should be coming from auth0. So auth0 might need to have some dashboard that says 'use these keys for this tenant'. But I'm sure there are many more ways to do this securely!

Copied from https://github.com/auth0-extensions/auth0-github-deploy/issues/59

**Comment by goodspark** [comment]
FWIW, I managed to do this myself in my own auth0 config repos by:

- Encrypting the `config.json` file for each tenant (in my case, dev and prod) with sops
- Writing a small script that decrypts these files and then calls `a0deploy`. Something like:

```sh
# After getting the proper credentials (eg. aws-vault)
sops -d path/to/${STACK}/config.json > config.json
a0deploy -v import -c config.json -i my_tenant_dir
```

I think we issue can be deferred or closed entirely. _Maybe_ some updates to the docs to give people pointers on how to do this themselves?

**Comment by fyockm** [comment]
@goodspark i think was addressed by https://github.com/auth0-extensions/auth0-deploy-extensions/pull/10
