### ISSUE TITLE
Github integration is using deprecated Github APIs

### ISSUE THREAD

**Issue by ScottFitz** [auth0-extensions/auth0-deploy-extensions#52]
Hi,
We started receiving notifications today that our Auth0 github integration is using deprecated Github APIs.

```

On February 5th, 2020 at 15:36 (UTC) your personal access token (XXXXX) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API:
.....snip

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

Is there a roadmap and/or timeline for when this will be addressed with the Auth0 github integration? or will we need to switch over to using the deploy-cli-tool instead of this integration?

Any information would be greatly appreciated.

**Comment by chelnak** [comment]
Interested in this too. I'm not the owner of the org so I keep having to explain what is going on.

**Comment by mithunshanbhag** [comment]
Is there any update on this issue? A lot of auth0 users are affected by this. 

Relevant auth0 community forum thread: https://community.auth0.com/t/the-github-social-connection-is-passing-access-token-as-part-of-a-query-param/37403/8

**Comment by toonvd** [comment]
Hi

It suffices to change the access_token param to an authorization header:

Authorization: token {access_token}

If you can point me to the place / repo where this should be adjusted, I would be more than happy to contribute.

**Comment by shawnmclean** [comment]
This will be worked on soon.

The extension is using an outdated version of the github npm package, we'll be swapping it out for the new octokit package, which will fix this error.

However, to address the question of switching to deploy-cli, we are now encouraging users to use that tool if they can as most updates will hit that tool much earlier than the extensions.

**Comment by ScottFitz** [comment]
Excellent, thanks @shawnmclean
