### ISSUE TITLE
Changes to tenant.yaml don't trigger update

### ISSUE THREAD

**Issue by brendanator** [auth0-extensions/auth0-deploy-extensions#53]
I pushed changes to `tenant.yaml`. The hook runs but returns http 202 with the body:
```json
{"message":"Request ignored, none of the Rules or Database Connection scripts were changed."}
```

The original `tenant.yaml` was generated by exporting with a0deploy yaml format.

Is or will this be supported?

**Comment by shawnmclean** [comment]
Hi @brendanator, is are you using the deploy-cli tool to export but importing with an extension? I'm not sure if that's a supported behavior but we are encouraging usage of the deploy-cli over the extensions if possible.
