### ISSUE TITLE
Support multi-part repository name for GitLab

### ISSUE THREAD

**Issue by nicosabena** [auth0-extensions/auth0-deploy-extensions#57]
Currently we only use repositories with two-part names ( `user/repo`), see:
* https://github.com/auth0-extensions/auth0-deploy-extensions/blob/d39a35a27629387210a1aa4eea35d3a8a7824239/server/lib/utils.js#L388-L402)
* https://github.com/auth0-extensions/auth0-deploy-extensions/blob/d39a35a27629387210a1aa4eea35d3a8a7824239/server/lib/providers/gitlab.js#L362-L382

GitLab, however, provides a "subgroups" feature (see https://docs.gitlab.com/ee/user/group/subgroups/#overview) which, when used, cause repository names to have more segments. E.g. a repository could be named `mycompany/myteam/mysubteam/myrepo`. 

So, at least for GitLab, we cannot assume a two-part name for repositories.

**Comment by aagavin** [comment]
Just a note that for gitlab, there can be more than one subgroup!
