### ISSUE TITLE
settings.json or database.json is not honored

### ISSUE THREAD

**Issue by goodspark** [auth0-extensions/auth0-deploy-extensions#6]
This is very similar to https://github.com/auth0-extensions/auth0-source-control-extension-tools/issues/58

I'm trying to configure my database connection (eg. disable signups) with the Github deploy extension. 

Based on the [readme in this repo](https://github.com/auth0-extensions/auth0-deploy-extensions#organize-your-repository), this extension supports something called `settings.json` in the `database-connections` folder.

However, there's no further documentation on what this file is and its expected schema.

So I tried the format mentioned in the above issue and the deploys are not honoring the settings.

What am I missing?

**Comment by goodspark** [comment]
It looks like the format seen in the other issue matches the request schema of the create connection API.

https://auth0.com/docs/api/management/v2#!/Connections/post_connections

So it seems reasonable to assume that this should work. Does the extension currently not support this?

**Comment by wingrunr21** [comment]
It would be nice if this was documented.
