### ISSUE TITLE
Incomplete deployments on Github Deploy

### ISSUE THREAD

**Issue by theogravity** [auth0-extensions/auth0-deploy-extensions#62]
Hi,

We've been going back and forth with support on this issue where we're seeing incomplete deployments on the Github deploy extension for over a week now, and was wondering if we could do a screen share as we can generally replicate the issue.

https://support.auth0.com/tickets/00452451

**Comment by shawnmclean** [comment]
Hi, we're now waiting on the dependency changes in https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/91 to hit our webtask before we can update this extension.

**Comment by theogravity** [comment]
Thanks, the submitted PR should hopefully help resolve most of our issues.
