### ISSUE TITLE
Feature request: support for MS Teams webhooks

### ISSUE THREAD

**Issue by kachniarzk** [auth0-extensions/auth0-deploy-extensions#65]
The current implementation allows getting notifications about deployments on Slack.

More and more development teams are using Microsoft Teams(1), so it would be great if there is a possibility to get similar notifications there. The configuration could be very similar to Slack, like MS_TEAMS_INCOMING_WEBHOOK_URL.

Source:
1. https://www.businessinsider.in/tech/enterprise/news/microsoft-teams-just-hit-20-million-daily-active-users-beating-its-rival-slack-once-again/articleshow/72129973.cms

**Comment by szamacz** [comment]
Love this proposal, this would make much people life easier
