### ISSUE TITLE
Node 12 Migration: Misconfiguration Error

### ISSUE THREAD

**Issue by Jazzex** [auth0-extensions/auth0-deploy-extensions#66]
After upgrading the node runtime in Auth0 to Node 12, the azure deployment script is broken. I have tried saving the settings multiple times, and uninstalling/reinstalling. 

I end up with this error:

invalid_request: Client attempting to use unregistered redirect URI: https://[tenant].us8.webtask.io/[id]

**Comment by Jazzex** [comment]
I ended up re-writing our deployment process to use the Auth0 Deploy CLI (https://github.com/auth0/auth0-deploy-cli)

I'm not sure what happened with this extension but I still suggest the Auth0 team looks into this issue.

**Comment by shushen** [comment]
Thanks for the report. I'm glad that you get it working with deploy-cli.
Please refer to our upgrade guide for extensions: https://auth0.com/docs/product-lifecycle/deprecations-and-migrations/migrate-to-nodejs-12#update-extensions, where we provide instructions to deal with this specific error.
