### ISSUE TITLE
Support for https://auth0.com/docs/hooks

### ISSUE THREAD

**Issue by audunhalland** [auth0-extensions/auth0-deploy-extensions#7]
Currently I see no way to manage and deploy hooks using deploy extension. Potentially because of hooks still being in "beta"?

Hoping for comments in this thread if support for hooks is planned.

**Comment by GaelS** [comment]
Looking forward to knowing more about this as well :)

**Comment by cb16** [comment]
I'm interested in this feature as well :D

**Comment by nfadili** [comment]
I am also curious if this is planned to be supported. Hooks are currently one of only a few things that our tenants don't have backed by version control :D
