### ISSUE TITLE
Missing GitHub Deploy (and all extensions) functionality to manage Anomaly Detection

### ISSUE THREAD

**Issue by dominicfallows** [auth0-extensions/auth0-deploy-extensions#85]
As per the details in https://github.com/auth0/auth0-deploy-cli/issues/250 (for auth0-deploy-cli) there is no functionality to manage Anomaly Detection via Configuration-as-Code extensions. 

In the Dashboard Admin there is a standalone section "Anomaly Detection" to control those settings.

In the JSON files of either the GitHub deploy or the CLI deploy extensions there is a single `brute_force_protection` setting that is directly in the DB connection files (not a tenant-level setting as per the Dashboard Admin > Anomaly Detection > Brute-force Protection)

Question 1) How do we control the 3 x Anomaly Detection settings via `JSON` config?

- Bot Detection
- Brute-force Protection
- Breached-password Detection

Question 2) How do the individual DB connection JSON `brute_force_protection` booleans relate to the tenant-level Dashboard Admin > Anomaly Detection > Brute-force Protection settings? There are multiple DB connections, but only a single Dashboard Admin tenant-level setting. Do these JSON settings have an effect?

**Comment by dominicfallows** [comment]
There has been no fix or development from what I can tell, so the issue is still relevant

**Comment by ddkserv** [comment]
Thumbs up. Needs this too...
