### ISSUE TITLE
Migrate to Management API v2 Endpoint Paginated Queries

### ISSUE THREAD

**Issue by nfadili** [auth0-extensions/auth0-deploy-extensions#86]
We have noticed a number of deprecation notices in our logs when deploying with the Github Deployment extension. A migration guide has been published by Auth0 for this - https://auth0.com/docs/product-lifecycle/deprecations-and-migrations/migrate-to-paginated-queries

Looks like these deprecation notices will become errors starting January 26th 2021.

**Comment by shushen** [comment]
Hi there,

We've released v3.6 of the extensions that fixes for the paginated queries. Please kindly upgrade from the Auth0 management dashboard. Thanks for your patience and the report!

Best,
Shu
