### ISSUE TITLE
webauthn guardian factor violates schema - Fails deployment

### ISSUE THREAD

**Issue by MGough** [auth0-extensions/auth0-deploy-extensions#88]
I exported our config from Auth0 using the CLI, then tried to redeploy it using the Github Deployment extension. When exporting it included `guardian/factors/webauthn-roaming.json`, but this was rejected by the schema as it's not present in the enum. 

I see that WebAuthn is a BETA feature, but it's not ideal in terms of user experience to be unable to import something which was exported only moments beforehand. Perhaps BETA features should not be exported by default if it's not possible to import them?

Error message was: 
```
Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
```

**Comment by shushen** [comment]
Thanks for the report. This should have been fixed in v3.7.0.
