### ISSUE TITLE
BUG: Incorrect parsing of GitLab repository URL on v3.7

### ISSUE THREAD

**Issue by foogunlana** [auth0-extensions/auth0-deploy-extensions#99]
### Steps to reproduce.

1. Create a gitlab repository nested under a sub-group. For instance "https://gitlab.com/username/subgroupname/reponame"

2. Install the gitlab deployments extension in the auth0 GUI, with this repo

3. Go to the "deployments" tab, and click deploy

### Expected behaviour

A deployment occurs

### Actual behaviour

Network request returns with this error
```
{error: "ArgumentError", message: "Invalid repository: https://gitlab.com/username/subgroupname/reponame"}
```

It comes from [this function](https://github.com/auth0-extensions/auth0-deploy-extensions/blob/278c882427689b02919dd30f35af1bdc7eb40ba3/server/lib/utils.js#L421) which incorrectly parses the repository URL. 

Splitting the subgroup repo URL gives 6 parts.
![Screenshot 2021-01-06 at 17 56 29](https://user-images.githubusercontent.com/5675998/103803478-87bb5280-5048-11eb-993e-b8fe2ebfd119.png)

I can open an MR to fix it, and properly identify the user and repo, unless for some reason auth0 doesn't want to support anything but 1 level of nesting in gitlab repositories.

It's also worth noting that I set up a different tenant and used the exact same configuration 1 month ago, and it worked perfectly fine with no issues. So this is strange. Perhaps this bug was introduced recently.

**Comment by shawnmclean** [comment]
Hi @foogunlana, thanks for submitting this bug.

You're free to submit a PR with a fix and I'll get it merged and released. Thanks for offering to fix that!

**Comment by foogunlana** [comment]
No problem @shawnmclean I'll get on it
